name: Build and Release

on:
  push:
    branches: [ master, v2 ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-latest
            artifact_suffix: Windows-amd64
            build_method: standard
          - name: MacOS x86_64
            os: macos-15-intel
            artifact_suffix: macOS-amd64
            build_method: standard

          - name: MacOS aarch64
            os: macos-15
            artifact_suffix: macOS-arm64
            build_method: standard

    name: Build on ${{ matrix.name }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Setup Python and uv
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: python -m pip install --upgrade pip uv

    - name: Install Dependencies
      run: uv sync

    - name: Update Version File and Get Version
      id: get_version
      shell: bash
      run: |
        pip install toml
        version=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "Successfully found version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Replace Version in Python File using sed
      shell: bash
      run: |
        VERSION_NUMBER="${{ steps.get_version.outputs.version }}"
        VERSION_FILE="src/bililive_utility/utils/version.py"
        
        NEW_LINE="VERSION = Version(version=\"$VERSION_NUMBER\")"

        echo "Writing version '$VERSION_NUMBER' to $VERSION_FILE"
        sed -i "/^VERSION = Version(/,/^)/c\\$NEW_LINE" "$VERSION_FILE"

        echo "File content replacement completed:"
        cat "$VERSION_FILE"

    - name: Build Application with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        ./script/build.ps1

    - name: Build Application with PyInstaller (MacOS)
      if: matrix.os == 'macos-15' || matrix.os == 'macos-15-intel'
      run: |
        ./script/build.sh
        
    - name: Create DMG for MacOS
      if: matrix.os == 'macos-15' || matrix.os == 'macos-15-intel'
      run: |
        ./script/create-dmg.sh

    # - name: Move static folder
    #   run: |
    #     mv "dist/BiliLive Utility/_internal/static" "dist/BiliLive Utility/static"
    #   shell: bash
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BiliLive-Utility-${{ matrix.artifact_suffix }}-${{ steps.get_version.outputs.version }}
        path: dist/BiliLive Utility/
