name: Build and Release

on:
  push:
    branches: [ master, v2 ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  before-build:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Get Version
      id: get_version
      run: python scripts/0-replace-version.py

  build:
    needs: before-build
    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-latest
            artifact_suffix: Windows-amd64
            build_cmd: ./scripts/1-build.ps1
          - name: MacOS x86_64
            os: macos-15-intel
            artifact_suffix: macOS-amd64
            build_cmd: |
              chmod +x scripts/1-build.sh
              chmod +x scripts/2-create-dmg.sh
              ./scripts/1-build.sh
              ./scripts/2-create-dmg.sh
          - name: MacOS aarch64
            os: macos-15
            artifact_suffix: macOS-arm64
            build_cmd: |
              chmod +x scripts/1-build.sh
              chmod +x scripts/2-create-dmg.sh
              ./scripts/1-build.sh
              ./scripts/2-create-dmg.sh

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv and Dependencies
      shell: bash
      run: |
        python -m pip install uv
        uv sync
        
        # Add .venv to PATH
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "$PWD/.venv/Scripts" >> $GITHUB_PATH
        else
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
        fi

    - name: Apply Version
      env:
        AG_VERSION: ${{ needs.before-build.outputs.version }}
      run: |
        python scripts/0-replace-version.py


    - uses: gerlero/brew-install@v1
      if: matrix.os == 'macos-15' || matrix.os == 'macos-15-intel'
      with:
        packages: create-dmg

    - name: Build Application
      env:
        AG_VERSION: ${{ needs.before-build.outputs.version }}
      run: ${{ matrix.build_cmd }}

    - name: Set DMG icon
      if: matrix.os == 'macos-15' || matrix.os == 'macos-15-intel'
      run: |
        chmod +x scripts/3-seticon
        for dmg in dist/*.dmg; do
          ./scripts/3-seticon static/favicon.icns "$dmg"
        done

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BiliLive-Utility-v${{ needs.before-build.outputs.version }}-${{ matrix.artifact_suffix }}
        path: dist/
